### ISSUE TITLE
Slight MIT Mask Misalignment

### ISSUE THREAD

**Issue by rbrenesh** [greyltc/layouts#1]
I didn't notice any misalignment between the mask and the devices until today when I actually put some our cells on a backlit surface. There is a slight misalignment along the width of the mask (see below). Do you have the mask files somewhere? We can reduce the width and try to get a few ordered here on our end.

![img_20190227_105151](https://user-images.githubusercontent.com/33428877/53505452-d4fc2f80-3a81-11e9-9625-497b857d3a30.jpg)
![img_20190227_110549](https://user-images.githubusercontent.com/33428877/53505457-d9284d00-3a81-11e9-9841-cd8432fef6df.jpg)

**Comment by greyltc** [comment]
ah crap. The file I drew from the .ai file you guys gave me and subsequently used to place the light mask order and design the substrate holder PCBs is here:
https://github.com/mutovis/layouts/blob/master/MIT/layout.dxf

you can download it with
```
wget -L https://raw.githubusercontent.com/mutovis/layouts/master/MIT/layout.dxf
```
The current version of it (and the one I used to make the order) looks like this:
![image](https://user-images.githubusercontent.com/16778174/53518900-ee28ce80-3ac9-11e9-8993-5d956cbbfe94.png)
I think it's not offset or anything. Do you see any problems there?

I was a bit worried about the 0.1mm lightmask tolerance (the amount of offset I used to come in from the edges of the device to define the light mask holes size, shall I edit that to be 0.3mm?

**Comment by greyltc** [comment]
The light masks I included with your kit are expected to be perfectly centered on a 25.146 x 25.146 mm square. I've measured some extras from your order I have here with calipers and they look like what I expect them to be.

Here's a thought:

Can it be that one of your fabrication steps is maybe such that the devices don't end up perfectly centered on the substrate? Like often there is some extra room in say the evaporator substrate holder to accommodate glass that's not all cut perfectly and the convention is to push the pixel 1 corner into maybe the upper right hand corner of the holder. This could result in the metal going down maybe not exactly centered on the substrate (depending on the size of the glass). That's kinda what this looks like to me.

Can we get precise drawings of both the substrate holder in your evaporator and the evaporator metal mask and exactly how those two things are meant to be aligned?

**Comment by rbrenesh** [comment]
Yes I think this is the issue. It's not an issue on your design, it's more
about the variability of the evaporation of the electrodes. I think
increasing the tolerance to 0.3mm might help with that variability.

We have the designs for the holder and the evaporation mask in SolidWorks,
do you want me to convert them to a specific file format or should I just
send those as is to you?
